### ISSUE TITLE
Add "garbage time" filter

### ISSUE THREAD

**Issue by Alex-At-Home** [Alex-At-Home/cbb-on-off-analyzer#40]
(could replace the walk-on filter for now, since it accomplishes basically the same thing)

Have a look at what people are defining as garbage time, but something like:
* 20 points with <=2 mins remaining
* 30 points with <= 3? mins remaining?

**Comment by Alex-At-Home** [comment]
Some notes:

https://kenpom.com/blog/the-simplest-proof-that-overtime-data-is-useful-and-that-garbage-time-exists/

18pts with 5 mins remaining ... seems a little aggressive
15pts with 2 mins remaining

**Comment by Alex-At-Home** [comment]
http://www.slate.com/articles/sports/sports_nut/2008/03/the_lead_is_safe.html

* Take the number of points one team is ahead.
Subtract three.
* Add a half-point if the team that is ahead has the ball, and subtract a half-point if the other team has the ball. (Numbers less than zero become zero.)
* Square that.
* If the result is greater than the number of seconds left in the game, the lead is safe.

**Comment by AlexP-Elastic** [comment]
This seems to work:

```groovy
def diff = doc["score_info.start_diff"].value;
def abs_diff = Math.abs(diff) - 0.5;
def diff_to_sq = abs_diff >= 0.0 ? abs_diff : 0.0;
def diff_sq = diff_to_sq*diff_to_sq;
// (OT case filtered out)
def remaining = (40.0 - doc["start_min"].value)*60.0;
diff_sq > remaining;
```
